# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Users',
        ),
    ]
