# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170919_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=68)),
                ('confirm_password', models.CharField(max_length=68)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
