# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170920_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password2',
        ),
    ]
