# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20170924_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='password', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='password2', max_length=255),
            preserve_default=False,
        ),
    ]
