# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_answertype_createsurvey_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertype',
            name='date_field',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='answertype',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='answertype',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answertype',
            name='time_field',
            field=models.TimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='answertype',
            name='yes_no',
            field=models.NullBooleanField(),
        ),
    ]
