# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertype',
            name='question_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='answertype',
            name='survey_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey.CreateSurvey'),
        ),
        migrations.AddField(
            model_name='answertype',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='createsurvey',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='survey_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey.CreateSurvey'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
