# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20171012_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertype',
            name='string',
            field=models.TextField(null=True),
        ),
    ]
