# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_answertype_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertype',
            name='question_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='answertype',
            name='survey_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.CreateSurvey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.CreateSurvey'),
        ),
    ]
