# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171015_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.TextField(default='openEnded', verbose_name=(('OPEN ENDED', 'openEnded'), ('SINGLE CHOICE', 'singleChoice'), ('BIPOLAR', 'bipolar'), ('RATING', 'rating'), ('MULTIPLE ANSWERS', 'multipleChoice'), ('DATE/TIME', 'dateTime'))),
        ),
    ]
