# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20171025_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoices',
            name='question_name',
        ),
        migrations.RemoveField(
            model_name='questionchoices',
            name='survey_name',
        ),
        migrations.RemoveField(
            model_name='questionchoices',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='possible_choices',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(default='openEnded', verbose_name=(('OPEN ENDED', 'openEnded'), ('SINGLE CHOICE', 'singleChoice'), ('BIPOLAR', 'Bipolar'), ('RATING', 'Rating'), ('MULTIPLE ANSWERS', 'multipleChoice'), ('DATE/TIME', 'dateTime'))),
        ),
        migrations.DeleteModel(
            name='QuestionChoices',
        ),
    ]
